"""empty message

Revision ID: 3587a131b095
Revises: c3154667766f
Create Date: 2022-02-17 14:57:46.915038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3587a131b095'
down_revision = 'c3154667766f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'is_verified')
    # ### end Alembic commands ###
