"""empty message

Revision ID: 927c5cd878a6
Revises: beea2bae09d9
Create Date: 2022-12-13 13:17:07.865376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927c5cd878a6'
down_revision = 'beea2bae09d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_messages', 'chat', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'chat_id')
    # ### end Alembic commands ###
