"""empty message

Revision ID: beea2bae09d9
Revises: aabafa219560
Create Date: 2022-12-13 12:33:06.603717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'beea2bae09d9'
down_revision = 'aabafa219560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.drop_index('ix_users_firstname', table_name='users')
    op.drop_index('ix_users_lastname', table_name='users')
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastname', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('firstname', mysql.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.create_index('ix_users_lastname', 'users', ['lastname'], unique=True)
    op.create_index('ix_users_firstname', 'users', ['firstname'], unique=True)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
